/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApexChart: typeof import('./src/components/ApexChart.vue')['default']
    AppMenu: typeof import('./src/components/AppMenu/index.vue')['default']
    ApprovalsSnippet: typeof import('./src/components/ApprovalsSnippet.vue')['default']
    BBadge: typeof import('bootstrap-vue-next')['BBadge']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardBody: typeof import('bootstrap-vue-next')['BCardBody']
    BCardHeader: typeof import('bootstrap-vue-next')['BCardHeader']
    BCardTitle: typeof import('bootstrap-vue-next')['BCardTitle']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    ChartJs: typeof import('./src/components/ChartJs.vue')['default']
    CustomerDocumentsComponent: typeof import('./src/components/CustomerDocumentsComponent.vue')['default']
    DropDown: typeof import('./src/components/DropDown.vue')['default']
    FlatPicker: typeof import('./src/components/FlatPicker.vue')['default']
    Gallery: typeof import('./src/components/Gallery.vue')['default']
    InputMask: typeof import('./src/components/InputMask.vue')['default']
    JsVectorMap: typeof import('./src/components/JsVectorMap.vue')['default']
    JustGage: typeof import('./src/components/JustGage.vue')['default']
    KpiCard: typeof import('./src/components/dashboard/KpiCard.vue')['default']
    LogoBox: typeof import('./src/components/LogoBox.vue')['default']
    MenuItem: typeof import('./src/components/AppMenu/MenuItem.vue')['default']
    MenuItemLink: typeof import('./src/components/AppMenu/MenuItemLink.vue')['default']
    MenuItemWithChildren: typeof import('./src/components/AppMenu/MenuItemWithChildren.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarSearch: typeof import('./src/components/SidebarSearch/SidebarSearch.vue')['default']
    UIComponentCard: typeof import('./src/components/UIComponentCard.vue')['default']
  }
}
